// <auto-generated />
using System;
using Estimator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estimator.Migrations
{
    [DbContext(typeof(EstimatorContext))]
    partial class EstimatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estimator.Models.AsuViews.DefectedType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("DefectCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElementImportID")
                        .HasColumnType("int");

                    b.Property<bool>("NormTY")
                        .HasColumnType("bit");

                    b.Property<string>("ProtokolNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RFA")
                        .HasColumnType("bit");

                    b.Property<string>("TY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeNominal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Unrecommend")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ElementImportID");

                    b.ToTable("DefectedType");
                });

            modelBuilder.Entity("Estimator.Models.CalcFactor", b =>
                {
                    b.Property<int>("CalcFactorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalcFactorID"));

                    b.Property<int>("CompanyHistoryID")
                        .HasColumnType("int");

                    b.Property<string>("FactorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FactorValue")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("CalcFactorID");

                    b.HasIndex("CompanyHistoryID");

                    b.ToTable("CalcFactor", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.ClassECB", b =>
                {
                    b.Property<int>("ClassECBID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassECBID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClassECBID");

                    b.ToTable("ClassECB", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Estimator.Models.CompanyHistory", b =>
                {
                    b.Property<int>("CompanyHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyHistoryID"));

                    b.Property<decimal>("AdditionalSalary")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Margin")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("OverHead")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PensionTax")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("YearOfNorms")
                        .HasColumnType("int");

                    b.HasKey("CompanyHistoryID");

                    b.ToTable("CompanyHistory", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.CustomerRequest", b =>
                {
                    b.Property<int>("CustomerRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerRequestID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("HidePackingSample")
                        .HasColumnType("bit");

                    b.Property<bool>("HideSamplePrice")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProceed")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModificateUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("MaterialRate")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("ModificateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCustomerRequestID")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TestProgramID")
                        .HasColumnType("int");

                    b.Property<bool>("UseImport")
                        .HasColumnType("bit");

                    b.Property<bool>("UsePurchaseElements")
                        .HasColumnType("bit");

                    b.HasKey("CustomerRequestID");

                    b.HasIndex("CreateUserID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("LastModificateUserID");

                    b.HasIndex("ParentCustomerRequestID")
                        .IsUnique()
                        .HasFilter("[ParentCustomerRequestID] IS NOT NULL");

                    b.HasIndex("TestProgramID");

                    b.ToTable("CustomerRequests", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.ElementImport", b =>
                {
                    b.Property<int>("ElementImportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementImportID"));

                    b.Property<int>("CustomerRequestID")
                        .HasColumnType("int");

                    b.Property<int>("DatasheetColumn")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryTimeColumn")
                        .HasColumnType("int");

                    b.Property<int>("DownloadPriceColumn")
                        .HasColumnType("int");

                    b.Property<int>("ElementContractorPriceColumn")
                        .HasColumnType("int");

                    b.Property<int>("ElementCountColumn")
                        .HasColumnType("int");

                    b.Property<int>("ElementKitPriceColumn")
                        .HasColumnType("int");

                    b.Property<int>("ElementNameColumn")
                        .HasColumnType("int");

                    b.Property<int>("ElementPriceColumn")
                        .HasColumnType("int");

                    b.Property<int>("ElementTypeKeyColumn")
                        .HasColumnType("int");

                    b.Property<bool>("FileUploaded")
                        .HasColumnType("bit");

                    b.Property<bool>("FirstRowIsHeader")
                        .HasColumnType("bit");

                    b.Property<int>("FirstRowNumber")
                        .HasColumnType("int");

                    b.Property<bool>("GroupSameTypes")
                        .HasColumnType("bit");

                    b.Property<bool>("ImportDatasheet")
                        .HasColumnType("bit");

                    b.Property<bool>("ImportDeliveryTime")
                        .HasColumnType("bit");

                    b.Property<bool>("ImportElementContractorPrice")
                        .HasColumnType("bit");

                    b.Property<bool>("ImportElementPrice")
                        .HasColumnType("bit");

                    b.Property<bool>("ImportElementКitPrice")
                        .HasColumnType("bit");

                    b.Property<bool>("ImportQualityLevel")
                        .HasColumnType("bit");

                    b.Property<bool>("ImportSampleSize")
                        .HasColumnType("bit");

                    b.Property<int>("LastRowNumber")
                        .HasColumnType("int");

                    b.Property<int>("QualityLevelColumn")
                        .HasColumnType("int");

                    b.Property<int>("SampleSizeColumn")
                        .HasColumnType("int");

                    b.Property<bool>("UseLastCalculation")
                        .HasColumnType("bit");

                    b.Property<bool>("UseLastRowNumber")
                        .HasColumnType("bit");

                    b.HasKey("ElementImportID");

                    b.HasIndex("CustomerRequestID");

                    b.ToTable("ElementImports");
                });

            modelBuilder.Entity("Estimator.Models.ElementKey", b =>
                {
                    b.Property<int>("ElementKeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementKeyID"));

                    b.Property<int>("ElementTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElementKeyID");

                    b.HasIndex("ElementTypeID");

                    b.ToTable("ElementKey");
                });

            modelBuilder.Entity("Estimator.Models.ElementPriceHistory", b =>
                {
                    b.Property<int>("ElementPriceHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementPriceHistoryID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerRequestID")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryTime")
                        .HasColumnType("int");

                    b.Property<string>("ElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinPackingSize")
                        .HasColumnType("int");

                    b.Property<int>("PackingSample")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("PriceType")
                        .HasColumnType("int");

                    b.Property<int?>("XLSXElementTypeID")
                        .HasColumnType("int");

                    b.HasKey("ElementPriceHistoryID");

                    b.HasIndex("XLSXElementTypeID");

                    b.ToTable("ElementPriceHistory");
                });

            modelBuilder.Entity("Estimator.Models.ElementType", b =>
                {
                    b.Property<int>("ElementTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementTypeID"));

                    b.Property<bool>("CheckInAsu")
                        .HasColumnType("bit");

                    b.Property<int?>("ChildElementTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ClassECBID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.HasKey("ElementTypeID");

                    b.HasIndex("ClassECBID");

                    b.HasIndex("ProgramID");

                    b.ToTable("ElementType", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.ImFileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImportData");
                });

            modelBuilder.Entity("Estimator.Models.Operation", b =>
                {
                    b.Property<int>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("DPO")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExecuteDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("OperationGroupID")
                        .HasColumnType("int");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.HasKey("OperationID");

                    b.HasIndex("OperationGroupID");

                    b.ToTable("Operation", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.OperationGroup", b =>
                {
                    b.Property<int>("OperationGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationGroupID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OperationGroupID");

                    b.ToTable("OperationGroup", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int?>("DeliveryTime")
                        .HasColumnType("int");

                    b.Property<int>("MinPackingSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackingSample")
                        .HasColumnType("int");

                    b.Property<int?>("PriceItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PriceListId")
                        .HasColumnType("int");

                    b.Property<string>("Property0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VniirId")
                        .HasColumnType("int");

                    b.HasKey("PriceId");

                    b.HasIndex("PriceItemTypeId");

                    b.HasIndex("PriceListId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Estimator.Models.PriceItemType", b =>
                {
                    b.Property<int>("PriceItemTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceItemTypeID"));

                    b.Property<string>("PriceItemTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriceItemTypeID");

                    b.ToTable("PriceItemType");
                });

            modelBuilder.Entity("Estimator.Models.PriceList", b =>
                {
                    b.Property<int>("PriceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceListId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceItemTypeID")
                        .HasColumnType("int");

                    b.Property<string>("ScanOfPrice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriceListId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PriceItemTypeID");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("Estimator.Models.PricePropertyName", b =>
                {
                    b.Property<int>("PricePropertyNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricePropertyNameId"));

                    b.Property<string>("ElementPropertyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PricePropertyNameId");

                    b.HasIndex("PriceItemTypeId");

                    b.ToTable("PricePropertyName");
                });

            modelBuilder.Entity("Estimator.Models.Qualification", b =>
                {
                    b.Property<int>("QualificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QualificationID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QualificationID");

                    b.ToTable("Qualification", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.RequestElementType", b =>
                {
                    b.Property<int>("RequestElementTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestElementTypeID"));

                    b.Property<int>("BatchCount")
                        .HasColumnType("int");

                    b.Property<int>("CustomerRequestID")
                        .HasColumnType("int");

                    b.Property<int?>("ElementTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<int>("KitCount")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("RequestElementTypeID");

                    b.HasIndex("CustomerRequestID");

                    b.HasIndex("ElementTypeID");

                    b.ToTable("RequestElementType", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.RequestOperation", b =>
                {
                    b.Property<int>("RequestOperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestOperationID"));

                    b.Property<int>("ExecuteCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsExecute")
                        .HasColumnType("bit");

                    b.Property<int>("RequestElementTypeID")
                        .HasColumnType("int");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<int?>("TestChainItemID")
                        .HasColumnType("int");

                    b.HasKey("RequestOperationID");

                    b.HasIndex("RequestElementTypeID");

                    b.HasIndex("TestChainItemID");

                    b.ToTable("RequestOperation", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.RuChipsDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeManufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subgroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechCondition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DirVniir");
                });

            modelBuilder.Entity("Estimator.Models.StaffItem", b =>
                {
                    b.Property<int>("StaffItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffItemID"));

                    b.Property<int>("CompanyHistoryID")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("QualificationID")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("StaffItemID");

                    b.HasIndex("CompanyHistoryID");

                    b.HasIndex("QualificationID");

                    b.ToTable("StaffItem", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.TestAction", b =>
                {
                    b.Property<int>("TestActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestActionID"));

                    b.Property<int>("BatchLabor")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemLabor")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("KitLabor")
                        .HasColumnType("int");

                    b.Property<int>("QualificationID")
                        .HasColumnType("int");

                    b.Property<int>("TestChainItemID")
                        .HasColumnType("int");

                    b.HasKey("TestActionID");

                    b.HasIndex("QualificationID");

                    b.HasIndex("TestChainItemID");

                    b.ToTable("TestAction", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.TestChainItem", b =>
                {
                    b.Property<int>("TestChainItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestChainItemID"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ElementTypeID")
                        .HasColumnType("int");

                    b.Property<int>("GroupOperation")
                        .HasColumnType("int");

                    b.Property<int>("OperationID")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("TestChainItemID");

                    b.HasIndex("ElementTypeID");

                    b.HasIndex("OperationID");

                    b.ToTable("TestChainItem", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.TestProgram", b =>
                {
                    b.Property<int>("TestProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestProgramID"));

                    b.Property<bool>("AllowEditChain")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentProgramID")
                        .HasColumnType("int");

                    b.Property<bool>("UseRuChipsDB")
                        .HasColumnType("bit");

                    b.HasKey("TestProgramID");

                    b.ToTable("TestProgram", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.TestProgramTemplate", b =>
                {
                    b.Property<int>("TestProgramTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestProgramTemplateID"));

                    b.Property<string>("TemplateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestProgramID")
                        .HasColumnType("int");

                    b.HasKey("TestProgramTemplateID");

                    b.HasIndex("TestProgramID");

                    b.ToTable("TestProgramTemplate", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.TestProgramTemplateItem", b =>
                {
                    b.Property<int>("TestProgramTemplateItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestProgramTemplateItemID"));

                    b.Property<int>("ExecuteCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsExecute")
                        .HasColumnType("bit");

                    b.Property<int?>("OperationID")
                        .HasColumnType("int");

                    b.Property<int>("TestProgramTemplateID")
                        .HasColumnType("int");

                    b.HasKey("TestProgramTemplateItemID");

                    b.HasIndex("OperationID");

                    b.HasIndex("TestProgramTemplateID");

                    b.ToTable("TestProgramTemplateItem", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Estimator.Models.ViewModels.RequestOperationGroupView", b =>
                {
                    b.Property<int>("ExecuteCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsExecute")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationID")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.ToTable("RequestOperationGroupViews");
                });

            modelBuilder.Entity("Estimator.Models.XLSXElementType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AsuProtokolCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BeforeUploadedXLSXElementTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Datasheet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeliveryTime")
                        .HasColumnType("int");

                    b.Property<decimal>("ElementContractorPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("ElementCount")
                        .HasColumnType("int");

                    b.Property<int>("ElementImportID")
                        .HasColumnType("int");

                    b.Property<decimal>("ElementKitPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("ElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ElementPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("ElementTypeID")
                        .HasColumnType("int");

                    b.Property<string>("ElementTypeKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportedDatasheet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportedElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ImportedPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("ImportedQualificationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Included")
                        .HasColumnType("bit");

                    b.Property<int>("MinPackingSize")
                        .HasColumnType("int");

                    b.Property<int>("PackingSample")
                        .HasColumnType("int");

                    b.Property<int?>("PriceHistorySourceID")
                        .HasColumnType("int");

                    b.Property<int?>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("PriceType")
                        .HasColumnType("int");

                    b.Property<string>("QualificationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RowNum")
                        .HasColumnType("int");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<int?>("VniirItemId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ElementImportID");

                    b.HasIndex("PriceHistorySourceID");

                    b.HasIndex("PriceId");

                    b.HasIndex("VniirItemId");

                    b.ToTable("XLSXElementType", (string)null);
                });

            modelBuilder.Entity("Estimator.Models.AsuViews.DefectedType", b =>
                {
                    b.HasOne("Estimator.Models.ElementImport", null)
                        .WithMany("DefectedTypes")
                        .HasForeignKey("ElementImportID");
                });

            modelBuilder.Entity("Estimator.Models.CalcFactor", b =>
                {
                    b.HasOne("Estimator.Models.CompanyHistory", "CompanyHistory")
                        .WithMany("CalcFactors")
                        .HasForeignKey("CompanyHistoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyHistory");
                });

            modelBuilder.Entity("Estimator.Models.CustomerRequest", b =>
                {
                    b.HasOne("Estimator.Models.User", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserID");

                    b.HasOne("Estimator.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimator.Models.User", "LastModificateUser")
                        .WithMany()
                        .HasForeignKey("LastModificateUserID");

                    b.HasOne("Estimator.Models.CustomerRequest", "ParentCustomerRequest")
                        .WithOne("ChildCustomerRequest")
                        .HasForeignKey("Estimator.Models.CustomerRequest", "ParentCustomerRequestID");

                    b.HasOne("Estimator.Models.TestProgram", "Program")
                        .WithMany()
                        .HasForeignKey("TestProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("Customer");

                    b.Navigation("LastModificateUser");

                    b.Navigation("ParentCustomerRequest");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Estimator.Models.ElementImport", b =>
                {
                    b.HasOne("Estimator.Models.CustomerRequest", "CustomerRequest")
                        .WithMany()
                        .HasForeignKey("CustomerRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerRequest");
                });

            modelBuilder.Entity("Estimator.Models.ElementKey", b =>
                {
                    b.HasOne("Estimator.Models.ElementType", "ElementType")
                        .WithMany("Keys")
                        .HasForeignKey("ElementTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementType");
                });

            modelBuilder.Entity("Estimator.Models.ElementPriceHistory", b =>
                {
                    b.HasOne("Estimator.Models.XLSXElementType", "XLSXElementType")
                        .WithMany("PriceHistory")
                        .HasForeignKey("XLSXElementTypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("XLSXElementType");
                });

            modelBuilder.Entity("Estimator.Models.ElementType", b =>
                {
                    b.HasOne("Estimator.Models.ClassECB", "Class")
                        .WithMany()
                        .HasForeignKey("ClassECBID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimator.Models.TestProgram", "Program")
                        .WithMany("ElementntTypes")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Estimator.Models.Operation", b =>
                {
                    b.HasOne("Estimator.Models.OperationGroup", "OperationGroup")
                        .WithMany()
                        .HasForeignKey("OperationGroupID");

                    b.Navigation("OperationGroup");
                });

            modelBuilder.Entity("Estimator.Models.Price", b =>
                {
                    b.HasOne("Estimator.Models.PriceItemType", "PriceItemType")
                        .WithMany()
                        .HasForeignKey("PriceItemTypeId");

                    b.HasOne("Estimator.Models.PriceList", "PriceList")
                        .WithMany("PriceItems")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceItemType");

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("Estimator.Models.PriceList", b =>
                {
                    b.HasOne("Estimator.Models.Company", "Manufacture")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimator.Models.PriceItemType", "PriceItemType")
                        .WithMany()
                        .HasForeignKey("PriceItemTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacture");

                    b.Navigation("PriceItemType");
                });

            modelBuilder.Entity("Estimator.Models.PricePropertyName", b =>
                {
                    b.HasOne("Estimator.Models.PriceItemType", "PriceItemType")
                        .WithMany("PricePropertyNames")
                        .HasForeignKey("PriceItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceItemType");
                });

            modelBuilder.Entity("Estimator.Models.RequestElementType", b =>
                {
                    b.HasOne("Estimator.Models.CustomerRequest", "CustomerRequest")
                        .WithMany("RequestElementTypes")
                        .HasForeignKey("CustomerRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimator.Models.ElementType", "ElementType")
                        .WithMany()
                        .HasForeignKey("ElementTypeID");

                    b.Navigation("CustomerRequest");

                    b.Navigation("ElementType");
                });

            modelBuilder.Entity("Estimator.Models.RequestOperation", b =>
                {
                    b.HasOne("Estimator.Models.RequestElementType", "RequestElementType")
                        .WithMany("RequestOperations")
                        .HasForeignKey("RequestElementTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimator.Models.TestChainItem", "TestChainItem")
                        .WithMany()
                        .HasForeignKey("TestChainItemID");

                    b.Navigation("RequestElementType");

                    b.Navigation("TestChainItem");
                });

            modelBuilder.Entity("Estimator.Models.StaffItem", b =>
                {
                    b.HasOne("Estimator.Models.CompanyHistory", "Company")
                        .WithMany("Staff")
                        .HasForeignKey("CompanyHistoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimator.Models.Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Estimator.Models.TestAction", b =>
                {
                    b.HasOne("Estimator.Models.Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimator.Models.TestChainItem", "TestChainItem")
                        .WithMany("TestActions")
                        .HasForeignKey("TestChainItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("TestChainItem");
                });

            modelBuilder.Entity("Estimator.Models.TestChainItem", b =>
                {
                    b.HasOne("Estimator.Models.ElementType", "ElementType")
                        .WithMany("ChainItems")
                        .HasForeignKey("ElementTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimator.Models.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementType");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Estimator.Models.TestProgramTemplate", b =>
                {
                    b.HasOne("Estimator.Models.TestProgram", "Program")
                        .WithMany("Templates")
                        .HasForeignKey("TestProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Estimator.Models.TestProgramTemplateItem", b =>
                {
                    b.HasOne("Estimator.Models.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationID");

                    b.HasOne("Estimator.Models.TestProgramTemplate", "ProgramTemplate")
                        .WithMany("TemplateItems")
                        .HasForeignKey("TestProgramTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("ProgramTemplate");
                });

            modelBuilder.Entity("Estimator.Models.XLSXElementType", b =>
                {
                    b.HasOne("Estimator.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("Estimator.Models.ElementImport", "ElementImport")
                        .WithMany("XLSXElementTypes")
                        .HasForeignKey("ElementImportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimator.Models.ElementPriceHistory", "PriceHistorySource")
                        .WithMany()
                        .HasForeignKey("PriceHistorySourceID");

                    b.HasOne("Estimator.Models.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId");

                    b.HasOne("Estimator.Models.RuChipsDB", "VniirItem")
                        .WithMany()
                        .HasForeignKey("VniirItemId");

                    b.Navigation("Company");

                    b.Navigation("ElementImport");

                    b.Navigation("Price");

                    b.Navigation("PriceHistorySource");

                    b.Navigation("VniirItem");
                });

            modelBuilder.Entity("Estimator.Models.CompanyHistory", b =>
                {
                    b.Navigation("CalcFactors");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Estimator.Models.CustomerRequest", b =>
                {
                    b.Navigation("ChildCustomerRequest");

                    b.Navigation("RequestElementTypes");
                });

            modelBuilder.Entity("Estimator.Models.ElementImport", b =>
                {
                    b.Navigation("DefectedTypes");

                    b.Navigation("XLSXElementTypes");
                });

            modelBuilder.Entity("Estimator.Models.ElementType", b =>
                {
                    b.Navigation("ChainItems");

                    b.Navigation("Keys");
                });

            modelBuilder.Entity("Estimator.Models.PriceItemType", b =>
                {
                    b.Navigation("PricePropertyNames");
                });

            modelBuilder.Entity("Estimator.Models.PriceList", b =>
                {
                    b.Navigation("PriceItems");
                });

            modelBuilder.Entity("Estimator.Models.RequestElementType", b =>
                {
                    b.Navigation("RequestOperations");
                });

            modelBuilder.Entity("Estimator.Models.TestChainItem", b =>
                {
                    b.Navigation("TestActions");
                });

            modelBuilder.Entity("Estimator.Models.TestProgram", b =>
                {
                    b.Navigation("ElementntTypes");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Estimator.Models.TestProgramTemplate", b =>
                {
                    b.Navigation("TemplateItems");
                });

            modelBuilder.Entity("Estimator.Models.XLSXElementType", b =>
                {
                    b.Navigation("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
